### ISSUE TITLE
Static methods don´t show up

### ISSUE THREAD

**Issue by thatgreatAlice** [KybernetikGames/ultevents#1]
Trying to make an UltEvent that calls a static method but when I have to enter the type in the event menu, it doesnt´t allow me to enter any options. Any idea how to solve this.

**Comment by KybernetikGames** [comment]
What do you see when you click the "No Type Selected" button? It should look like this:
![image](https://github.com/KybernetikGames/ultevents/assets/43698611/c6b17f82-b130-4092-b8a8-1900ad1b5155)

**Comment by thatgreatAlice** [comment]
![Captura de pantalla (563)](https://github.com/KybernetikGames/ultevents/assets/66978485/a22ae4bf-eaf4-4f89-9c12-f07b7a11c93e)
it looks like this

**Comment by KybernetikGames** [comment]
Maybe try it in an empty project in case something else is interfering with it. I'm not sure how that would be possible, but since there are no errors that's all I can think of.

**Comment by KybernetikGames** [comment]
I'm closing this issue since I can't replicate it. Feel free to re-open if you have any additional information that might help track down what happened.
